In [44]:
import numpy as np
def PCA(data):
    mean = np.mean(data.T, axis=1)
    print("MEAN : ")
    print(mean)
    center = data - mean
    co_var = np.cov(center.T)
    print("Co-variance : ")
    print(co_var)
    e_values, e_vectors = np.linalg.eig(co_var)
    print("Eigen values : ")
    print(e_values)
    print("Eigen vectors : ")
    print(e_vectors)
    considered_e_values = np.array(e_vectors[0])
    print("Considered Eigen vector : ")
    print(considered_e_values)
    reduced = list()
    for i in center:
        reduced.append(considered_e_values.T.dot(i))
    return reduced

In [45]:
data = np.array([[7, 10], [10, 12], [13, 15],[5,7],[11,13]])
r_data = PCA(data)

MEAN : 
[ 9.2 11.4]
Co-variance : 
[[10.2   9.65]
 [ 9.65  9.3 ]]
Eigen values : 
[19.41048653  0.08951347]
Eigen vectors : 
[[ 0.72338838 -0.69044134]
 [ 0.69044134  0.72338838]]
Considered Eigen vector : 
[ 0.72338838 -0.69044134]


In [5]:
print("Reduced data ")
print(r_data)

Reduced data 
[-0.6248365625789577, 0.16444590070065263, 0.2632870213716006, -0.0002893004175933845, 0.19739294092430187]


In [7]:
import pandas as pd
data = pd.read_csv('./Social_Network_Ads.csv')

In [8]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [9]:
data.shape[0]

400

In [10]:
data = data[data['Gender']=='Female']
data.shape[0]

204

In [11]:
data = data.drop(columns=['Gender','User ID'])

In [12]:
data.head()

Age  EstimatedSalary  Purchased
2   26            43000          0
3   27            57000          0
6   27            84000          0
7   32           150000          1
9   35            65000          0

In [13]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)

In [17]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [19]:
from sklearn.metrics import accuracy_score
print("accuracy before : ", accuracy_score(y_test, y_pred))

accuracy before :  0.6129032258064516


In [26]:
x = data.iloc[:,:-1].values
x = PCA(x)
x = np.array(x).reshape(-1, 1)
y = data.iloc[:,-1].values

MEAN : 
[3.84117647e+01 7.17598039e+04]
Co-variance : 
[[1.17918285e+02 6.78530861e+04]
 [6.78530861e+04 1.26702084e+09]]
Eigen values : 
[1.14284531e+02 1.26702084e+09]
Eigen vectors : 
[[-9.99999999e-01 -5.35532566e-05]
 [ 5.35532566e-05 -9.99999999e-01]]
Considered Eigen vector : 
[-9.99999999e-01 -5.35532566e-05]


In [27]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)

In [29]:
model = LogisticRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [30]:
print("accuracy after : ", accuracy_score(y_test, y_pred))

accuracy after :  0.8225806451612904
